import React, { Component } from 'react';
import { Platform, StyleSheet, View, Image } from 'react-native';
import { Container, Header, Left, Body, Right, Button, Icon, Title, Content, List, ListItem, Text,Thumbnail} from 'native-base';
import {styles} from "../Styles";
import ListItemElement from '../components/ListItemElement';

export default class PHistory extends Component {
  state = {}
  render() {

    let navigation = this.props.navigation;
    
    return (
      
      <Container>
        {/* <View><Image source={require('../src/mocks/PHistory.png')} style={{width: 375,opacity: 20,  position: 'absolute'}}/></View> */}
        {/* <MockComponent mockScreen="phistory"/> */}
        <Header transparent>
          <Left>
            <Button transparent onPress={() => navigation.goBack()} >
              <Icon name='arrow-back' style={styles.backButton}/>
            </Button>
          </Left>
          <Body>
            <Title>Payment history</Title>
          </Body>
          <Right />
        </Header>
        <Header transparent style={{  }}>
        {/* <Header style={{ backgroundColor: "#fff" }}>  */}
          <Left style={{ flex: 1 }}>
            <Title>DATE</Title>
          </Left>
          <Body style={{ flex: 2, alignItems: "left" }}>
            <Title >DETAILS</Title>
          </Body>
          <Right style={{ flex: 1 }}>
            <Title>AMOUNT</Title>
          </Right>
        </Header>
        <Content>
          <List>
            {/* List is started */}
            <ListItemElement date="12.06.2019" amount="19,00" balancePos={true} StorageId="0"/>
            {/* New element sample */}
            <ListItemElement date="13.06.2019" amount="0,09" balancePos={false} StorageId="545652332"/>
            {/* New element sample */}
            <ListItemElement date="13.06.2019" amount="0,09" balancePos={false} StorageId="545652332"/>
            {/* New element sample  */}
            <ListItemElement date="12.06.2019" amount="19,00" balancePos={true} StorageId="0"/>
            {/* New element sample  */}
            <ListItemElement date="12.06.2019" amount="19,00" balancePos={true} StorageId="0"/>
            {/* New element sample  */}
            <ListItemElement date="12.06.2019" amount="19,00" balancePos={true} StorageId="0"/>
            {/* New element sample */}
            <ListItemElement date="13.06.2019" amount="0,09" balancePos={false} StorageId="545652332"/>
            {/* New element sample  */}
            <ListItemElement date="12.06.2019" amount="19,00" balancePos={true} StorageId="0"/>
            {/* List end */}
            
            {/* TODO: 
            Make list generated by elements array
            Done: Add styles container to listItems and list content elements
            Done: Divide master header and screen headers by view\components */}
          </List>
        </Content>
      </Container>
    );
  }
}